apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: monitoring
    spec:
      containers:
      - image: grafana/grafana:7.4.0
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana-default
        resources:
          limits:
            cpu: 150m
            memory: 250Mi
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/grafana/ 
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: grafana-local-data
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
