grafana_security:
  admin_user: admin
  admin_password: "{{ vault_grafana_password }}"

grafana_datasources:
- name: "Prometheus"
  type: "prometheus"
  access: "proxy"
  url: http://localhost:9090
  isDefault: true

grafana_dashboards: []
