{
 "title": "Node - detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(node_uname_info{job=\"$job\"},instance)"
   },
   {
    "name": "nic",
    "label": "nic",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))",
     "legendFormat": "sysload 15 avg"
    }
   ]
  },
  {
   "title": "sysload normalized by cpu count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\", job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\"}) by (cpu)) * 100",
     "legendFormat": "sysload 1 avg"
    },
    {
     "expr": "avg(node_load5{instance=\"$instance\", job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\"}) by (cpu)) * 100",
     "legendFormat": "sysload 5 avg"
    },
    {
     "expr": "avg(node_load15{instance=\"$instance\", job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\", job=\"$job\"}) by (cpu)) * 100",
     "legendFormat": "sysload 15 avg"
    }
   ]
  },
  {
   "title": "memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( (node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"} )) * 100",
     "legendFormat": "mem usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "total memory"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{instance=\"$instance\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{instance=\"$instance\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}))*100",
     "legendFormat": "root partition usage"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "root partition size"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "description": "system uptime",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\", job=\"$job\"} - node_boot_time_seconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  }
 ]
}