---
- name: Disable google services
  hosts: cluster
  become: true
  pre_tasks:
    - name: "disable google services : systemd unit"
      systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - google-osconfig-agent.service
        - google-guest-agent.service
      when: disable_google_services is defined

- name: Apply security restrictions
  hosts: cluster
  become: true
  pre_tasks:
    - name: "apt : update"
      apt:
        update_cache: yes
  roles:
  - dev-sec.ssh-hardening
  - dev-sec.os-hardening
  vars:
    ssh_permit_root_login: "without-password"
  post_tasks:
  - name: "iptables"
    block:
    - name: "iptables : flush INPUT chain"
      iptables:
          chain: INPUT
          flush: yes
    - name: "iptables : allow all loopback traffic"
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
    
    - name: "iptables : allow established connections"
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
    - name: "iptables : allow port ping traffic"
      iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: icmp
    - name: "iptables : allow port 22/SSH traffic"
      iptables:
        chain: INPUT
        destination_port: "22"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : install iptables-persistent"
      apt: 
        name: iptables-persistent
    - name: "iptables : persist"
      shell: iptables-save > /etc/iptables/rules.v4
    become: true