- name: Strict ip tables
  hosts: cluster
  become: true
  tasks:
  - name: "iptables"
    block:
    - name: "iptables : install iptables-persistent"
      ansible.builtin.apt: 
        name: "{{ item }}"
      loop:
      - iptables-persistent
      - iptables
    - name: "iptables : flush FORWARD chain"
      ansible.builtin.iptables:
          chain: FORWARD
          flush: true
    - name: "iptables : flush INPUT chain"
      ansible.builtin.iptables:
          chain: INPUT
          flush: true
    - name: "iptables : allow all loopback traffic"
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
    - name: "iptables : allow established connections"
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
    - name: "iptables : allow port ping traffic"
      ansible.builtin.iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: icmp
    - name: "iptables : allow port 22/SSH traffic"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "22"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : allow port 6443 traffic : Kubernetes API Server"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "6443"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : allow port udp/8472 traffic : Flannel VXLAN"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "8472"
        jump: ACCEPT
        protocol: udp
    - name: "iptables : allow port udp/51820 traffic : wireguard lan"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "51820"
        jump: ACCEPT
        protocol: udp
    - name: "iptables : allow port tcp/10250 traffic : Kubelet metrics"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "10250"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : allow port tcp/443 traffic : https"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "443"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : allow port tcp/80 traffic : http"
      ansible.builtin.iptables:
        chain: INPUT
        destination_port: "80"
        jump: ACCEPT
        protocol: tcp
    - name: "iptables : persist"
      shell: iptables-save > /etc/iptables/rules.v4
