---
- name: Setup prometheus
  hosts: prometheus
  pre_tasks:
  - name: setup os
    block:
    - name: "prometheus : setup os: create cert dir"
      file:
        path: /etc/ssl/prometheus/
        state: directory
        owner: "{{ ansible_user }}"
      become: yes
    - name: "prometheus : setup os: setup CA certificate"
      copy: 
        content: "{{ ownca_content }}"
        dest:  /etc/ssl/prometheus/{{ ansible_host }}.ca.crt

  roles:
  - cloudalchemy.prometheus
